---
title: "***iconr***, training datasets"
---

```{r, echo=FALSE}
# print(getwd())
# print(file.path("../logo", "iconr_logo.png"))
htmltools::img(src = knitr::image_uri(file.path("../doc/tutorial/img", "iconr_logo.png")),
               # htmltools::img(src = knitr::image_uri(file.path("img", "iconr_logo.png")), 
               # htmltools::img(src = knitr::image_uri(file.path(R.home("doc"), "html", "logo.jpg")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
# setwd("C:/Users/supernova/Dropbox/My PC (supernova-pc)/Documents/iconr/doc/datasets")
```

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(iconr)
library(dplyr)
library(knitr)
library(kableExtra)

downgit.root <- "https://downgit.github.io/#/home?url="
gh.root <- paste0(downgit.root, "https://github.com/zoometh/iconr/")
dir.root <- paste0(gh.root, "tree/master/doc/datasets/")
url.df <- c(paste0(dir.root, "stele%20bas%20aragon"),
            paste0(dir.root, "Valcamonica"),
            paste0(dir.root, "Pena%20Tu"))
url.ref <- c("https://doi.org/10.3989/gladius.2013.0002",
             "https://scholar.google.fr/scholar?hl=fr&as_sdt=0%2C5&q=Le+Pietre+degli+Dei%2C+menhir+e+stele+dell%27Eta+del+Rame+in+Valcamonica+e+Valtellina&btnG=",
             "https://doi.org/10.1016/j.anthro.2005.09.009")
df.dset <- data.frame("download" = c("stele bas aragon",
                                     "Valcamonica",
                                     "Pena Tu"),
                      "name" = c("Estelas Ibericas con Lanzas",
                                 "Ossimo",
                                 "Peña Tu style"),
                      "nb.decor" = c("5",
                                     "3",
                                     "5"),
                      "description" = c("Iron Age stelae with ranges of spears, writings, etc.",
                                        "Chalcolithic rock-art from Ossimo, Valcamonica",
                                        "Bell-Beaker stelae and rock-art"),
                      "drawings.references" = c("Vargas 2013",
                                                "Fedele 1994",
                                                "Ramírez 2005"),
                      stringsAsFactors = F)
```


These training datasets can be downloaded from the below dataframe. We also provide ready-to-use QGIS projects (.qgz) for each decoration:

```{r, echo = F}
# row.names(df.dset) <- df.dset$family
df.dset %>% 
  mutate(download = cell_spec(download, "html", link = url.df)) %>%
  mutate(drawings.references = cell_spec(drawings.references, "html", link = url.ref)) %>%
  kable("html", escape = FALSE, row.names = F) %>%
  kable_styling(bootstrap_options = c("hover", "condensed"), full_width = F)
```
