---
title: "***iconr***, examples on datasets"
author: "Thomas Huet, Jose M Pozo, Craig Alexander"
runtime: shiny
output: html_document
---

```{r, echo=FALSE}
# print(getwd())
# print(file.path("../logo", "iconr_logo.png"))
htmltools::img(src = knitr::image_uri(file.path("../tutorial/img", "iconr_logo.png")),
               # htmltools::img(src = knitr::image_uri(file.path("img", "iconr_logo.png")), 
               # htmltools::img(src = knitr::image_uri(file.path(R.home("doc"), "html", "logo.jpg")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
# setwd("C:/Users/supernova/Dropbox/My PC (supernova-pc)/Documents/iconr/doc/datasets")
```

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(iconr)
library(dplyr)
library(knitr)
library(kableExtra)

downgit.root <- "https://downgit.github.io/#/home?url="
gh.root <- paste0(downgit.root, "https://github.com/zoometh/iconr/")
dir.root <- paste0(gh.root, "tree/master/doc/datasets/")
url.df <- c(paste0(dir.root, "stele%20bas%20aragon"),
            paste0(dir.root, "Valcamonica"),
            paste0(dir.root, "Pena%20Tu"))
url.ref <- c("https://doi.org/10.3989/gladius.2013.0002",
             "https://scholar.google.fr/scholar?hl=fr&as_sdt=0%2C5&q=Le+Pietre+degli+Dei%2C+menhir+e+stele+dell%27Eta+del+Rame+in+Valcamonica+e+Valtellina&btnG=",
             "https://doi.org/10.1016/j.anthro.2005.09.009")
df.dset <- data.frame("download" = c("stele bas aragon",
                                     "Valcamonica",
                                     "Pena Tu"),
                      "name" = c("Estelas Ibericas con Lanzas",
                                 "Ossimo",
                                 "Peña Tu style"),
                      "nb.decor" = c("5",
                                     "3",
                                     "?"),
                      "description" = c("Iron Age stelae with ranges of spears, writings, etc.",
                                        "Chalcolithic rock-art from Ossimo, Valcamonica",
                                        "Bell-Beaker stelae and rock-art"),
                      "drawings.references" = c("Vargas 2013",
                                                "Fedele 1994",
                                                "Ramírez 2005"),
                      stringsAsFactors = F)
```

This RShiny app show examples on how to record the GUs and their proximity links with the ***iconr*** package ([`plot_dec()`](https://zoometh.github.io/iconr/reference/plot_dec_grph.html) function)

```{r eruptions, echo=FALSE}
famille <- df.dset$download
# famille <- c("stele bas aragon", "Valcamonica", "Pena Tu")
# setwd("..")
df <- read.csv(paste0(getwd(), "/", famille[1], "/imgs.csv"), sep=";")
def.dec <- paste0(df[1, "idf"], ".", df[1, "site"], "_", df[1, "decor"])

# datasets.path <- paste0(getwd(),"/docs/datasets")
datasets.path <- ""

ui <- fluidPage(
  sidebarPanel(
    selectInput("A", "family", choices = famille, selected = famille[1]),
    selectInput("B", "decoration", choices = def.dec),
    selectInput("C", "label", choices = c("id", "type"), selected = "type"),
    checkboxGroupInput("D", "graph elements",
                       c("nodes" = "nds",
                         "edges" = "eds"),
                       selected = c("nds", "eds"),
                       inline = T),
  ),
  mainPanel(plotOutput("plot"))
)

server <- function(input, output, session) {
  observe({
    choices_B <- read.csv(paste0("", input$A, "/imgs.csv"), sep=";")
    # choices_B <- read.csv(paste0(getwd(),"/docs/datasets/", input$A, "/imgs.csv"), sep=";")
    choices_B_dec <- paste0(choices_B$idf, ".", choices_B$site, "_", choices_B$decor)
    updateSelectInput(session, "B", choices = choices_B_dec)
  })
  output$plot <- renderPlot({
    a.idf <- as.numeric(unlist(strsplit(input$B,"\\."))[1])
    dataDir <- paste0(datasets.path, input$A)
    df <- read.csv(paste0(dataDir, "/imgs.csv"), sep=";")
    # Decoration to be plotted
    site <- df[a.idf, "site"]
    decor <- df[a.idf, "decor"]
    ## Read nodes, edges, and decorations
    # nodes
    if ("nds" %in% input$D){
      nds.df <- read_nds(site, decor, dataDir, format = "shp")
    } else {nds.df <- NULL}
    # edges
    if ("eds" %in% input$D){
      eds.df <- read_eds(site, decor, dataDir, format = "shp")
    } else {eds.df <- NULL}
    imgs <- read.table(paste0(dataDir, "/imgs.tsv"),
                       sep="\t", stringsAsFactors = FALSE, header = T)
    # Save the plot of nodes and edges with node variable "type" as labels
    # in png image format and return the image file name.
    plot_dec_grph(nds.df,
                  eds.df,
                  imgs,
                  site, decor,
                  dir = dataDir,
                  nd.var = input$C)
  })
}

shinyApp(ui, server)
```
These training datasets can be downloaded from the below dataframe. We also provide ready-to-use QGIS projects (.qgz) for each decoration:

```{r, echo = F}
# row.names(df.dset) <- df.dset$family
df.dset %>% 
  mutate(download = cell_spec(download, "html", link = url.df)) %>%
  mutate(drawings.references = cell_spec(drawings.references, "html", link = url.ref)) %>%
  kable("html", escape = FALSE, row.names = F) %>%
  kable_styling(bootstrap_options = c("hover", "condensed"), full_width = F)
```
